# Default values for techtalks web
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: nileshgule/techtalksweb
  tag: latest
  pullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst

service:
  type: LoadBalancer
  internalPort: 80

resources:
  limits:
    memory: 256Mi
    cpu: 1000m
  requests:
    memory: 128Mi
    cpu: 500m