apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: techtalksapi
  namespace: aks-part3
  labels:
    run: techtalksapi

spec:
  replicas: 1
  selector:
    matchLabels:
      run: techtalksapi
  
  template:
    metadata:
      labels:
        run: techtalksapi
    spec:
      initContainers:
        - name: init-myservice
          image: nileshgule/sqlclient
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "/opt/mssql-tools/bin/sqlcmd -S db-deployment -U sa -P January2018 -d master -i initialize-database.sql"
      containers:
      - name: techtalksapi
        image: nileshgule/techtalksapi
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:8080
          - name: ConnectionStrings__DefaultConnection
            value: "Data Source=db-deployment;Initial Catalog=TechTalksDB;User Id=SA;Password=January2018;MultipleActiveResultSets=True" 
        ports:
        - containerPort: 8080
          protocol: TCP
        
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst