apiVersion: v1
kind: Service
metadata:
  name: webfront
  # namespace: aks-part4
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 80
  # - port: 8088
  selector:
    run: webfront-deployment