apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: techtalksweb
  # namespace: aks-part4
  labels:
    run: webfront

spec:
  replicas: 1
  selector:
    matchLabels:
      run: webfront-deployment

  template:
    metadata:
      labels:
        run: webfront-deployment
    spec:
      containers:
      - name: techtalksweb
        image: nileshgule/techtalksweb
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: TechTalksAPIUrl
          value: "http://techtalksapi:8080/api/techtalks/"
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst