version: '3'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: sql1
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=June2018
    # tty: true
    
  techtalks.web:
    ports:
      - "80:80"
      
  techtalks.api:
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=sql.data,1433;Initial Catalog=TechTalksDB;User Id=SA;Password=June2018;MultipleActiveResultSets=True;
    depends_on: 
      - sql.data